name: Say Hi!
author: Heidi
description: Say Hi and show time

inputs:
  who-to-greet:
    description: Who to say hi to
    default: world
outputs:
  time:
    description: The time we were friendly

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
  
