name: Hi 🌍

on:
  push:
    branches: [main]
    paths: [HelloAction/**]
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who do we target for 🗨️'
        type: string
        required: true 
        default: attendees

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v6

      - name : test-the-action
        id : action-checker
        uses :  ./HelloAction
        with :
          who-to-greet: ${{ inputs.who-to-greet }}
      - name: show output
        run : echo "The time was ${{ steps.action-checker.outputs.time }} when the action said hello"
